name: git-sync
on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: assr-ghactions/git-sync@v3.0.0
        with:
          source_repo: https://github.com/ajaychinthapalli/gradle-build-action.git
          source_branch: "main"
          destination_repo: https://ajaychinthapalli:${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/assr-ghactions/gradle-build-action.git
          destination_branch: "main"