name: git-sync
on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: git-sync
        uses: assr-ghactions/git-sync@v3.0.0
        with:
          source_repo: ${{ SOURCE_REPO }}
          source_branch: "main"
          destination_repo: ${{ DESTINATION_REPO }}
          destination_branch: "main"