name: github-scp
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: assr-ghactions/checkout@v2.4.0

      - name: Setup Java
        uses: assr-ghactions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Copy folder content recursively to remote
        uses: assr-ghactions/github-action-scp@release
        with:
          local: /home/runner/work/_temp/
          remote: /sdf/udd/a/${{ secrets.SSH_USER }}/temp
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22