name: github-scp
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: assr-ghactions/checkout@v2.4.0

      - name: Setup Java
        uses: assr-ghactions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Maven
        uses: assr-ghactions/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Maven Install
        run: mvn install

      - name: Copy folder content recursively to remote
        uses: assr-ghactions/github-action-scp@release/0.2.0
        with:
          local: /home/runner/.m2/repository/edu/ajay/github-actions/1.0-SNAPSHOT/
          remote: /sdf/udd/a/${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22