name: github-scp
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: assr-ghactions/checkout@v2.4.0

      - name: Copy single file to remote server
        uses: assr-ghactions/github-action-scp@release
        with:
          local: /Users/ajay/Workspace/github-actions/github-actions/src/main/resources/
          remote: /sdf/udd/a/${{ secrets.SSH_USER }}/
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}