name: setup-node
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: assr-ghactions/checkout@v2.4.0
      - name: Setup Node
        uses: assr-ghactions/setup-node@v2.5.1
        with:
          node-version: '16'
      - name: Display Node Version
        run: node -v