name: setup-scala
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: assr-ghactions/checkout@v2.4.0
      - name: Setup Scala
        uses: assr-ghactions/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Compile
        run: sbt compile