name: setup-dotnet

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v2.4.0

      - name: Setup .NET Core
        uses: assr-ghactions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 3.1.301

      - name: .NET Version
        run: dotnet --version