name: setup-java
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: assr-ghactions/checkout@v2.4.0
      - name: Setup Java
        uses: assr-ghactions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Display Java Version
        run: java -version


